---
- hosts: all
  become: true
  tasks: 

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
 
#  - name: update repository index
#    ansible.builtin.dnf:
#      update_cache: yes
#    when: ansible_distribution == "Fedora"

#  - name: install httpd package
#    ansible.builtin.dnf:
#      name:
#        - httpd
#        - php
#      state: latest
#    when: ansible_distribution == "Fedora"
